services:
  - type: web
    name: second-support-accounting
    env: node
    plan: starter
    buildCommand: npm install && npm run build
    startCommand: npm start
    healthCheckPath: /health
    envVars:
      - key: NODE_ENV
        value: production
      - key: SESSION_SECRET
        generateValue: true
      - key: DATABASE_URL
        fromDatabase:
          name: second-support-db
          property: connectionString

databases:
  - name: second-support-db
    plan: starter
