import React, { createContext, useContext, useState, useEffect } from 'react';

type Language = 'en' | 'ar';

interface LanguageContextType {
  language: Language;
  setLanguage: (lang: Language) => void;
  t: (key: string) => string;
  isRTL: boolean;
}

const translations = {
  en: {
    // Login page
    'VoM Accounting Platform': 'Second Support Accounting Platform',
    'Sign in to your account': 'Sign in to your account',
    'Email Address': 'Email Address',
    'Password': 'Password',
    "I'm not a robot": "I'm not a robot",
    'Sign In': 'Sign In',
    'Logout': 'Logout',
    'Forgot your password?': 'Forgot your password?',
    'Test Credentials': 'Test Credentials',
    
    // Dashboard
    'VoM Accounting': 'VoM Accounting',
    'Financial Management Platform': 'Financial Management Platform',
    'Overview': 'Overview',
    'Invoices': 'Invoices',
    'Expenses': 'Expenses',
    'Reports': 'Reports',
    'ZATCA Compliance': 'ZATCA Compliance',
    'Quick Actions': 'Quick Actions',
    'New Invoice': 'New Invoice',
    'Import Data': 'Import Data',
    
    // Common UI
    'Welcome': 'Welcome',
    'Last visit today 1 day ago': 'Last visit today 1 day ago',
    'Export': 'Export',
    'Copy': 'Copy',
    'Print': 'Print',
    'Import': 'Import',
    'Filter': 'Filter',
    'Show': 'Show',
    'entries': 'entries',
    'Actions': 'Actions',
    'Active': 'Active',
    'Inactive': 'Inactive',
    'Back': 'Back',
    'Create': 'Create',
    'Code': 'Code',
    'Account': 'Account',
    'Phone': 'Phone',
    'Email': 'Email',
    'City': 'City',
    'Country': 'Country',
    'Value of Money': 'Value of Money',
    'All rights reserved © 2025 VoM': 'All rights reserved © 2025 VoM',
    
    // Financial Overview
    'Financial Overview': 'Financial Overview',
    'Track your business performance and key metrics': 'Track your business performance and key metrics',
    'Total Revenue': 'Total Revenue',
    'Active Invoices': 'Active Invoices',
    'Total Customers': 'Total Customers',
    'Monthly Expenses': 'Monthly Expenses',
    'Revenue Trend': 'Revenue Trend',
    'Recent Invoices': 'Recent Invoices',
    'View All Invoices': 'View All Invoices',
    
    // Invoice Management
    'Invoice Management': 'Invoice Management',
    'Create, manage and track your invoices': 'Create, manage and track your invoices',
    'Invoice #': 'Invoice #',
    'Amount': 'Amount',
    'Status': 'Status',
    'Date': 'Date',
    'Customer': 'Customer',
    'Paid': 'Paid',
    'Pending': 'Pending',
    'Draft': 'Draft',
    'Overdue': 'Overdue',
    'Due Date': 'Due Date',
    'Total': 'Total',
    'Subtotal': 'Subtotal',
    'Tax': 'Tax',
    'Discount': 'Discount',
    'Item': 'Item',
    'Description': 'Description',
    'Quantity': 'Quantity',
    'Price': 'Price',
    'Add Item': 'Add Item',
    'Save Invoice': 'Save Invoice',
    'Send Invoice': 'Send Invoice',
    'Preview': 'Preview',
    'Cancel': 'Cancel',
    'Save': 'Save',
    'Edit': 'Edit',
    'Delete': 'Delete',
    'View': 'View',
    'Invoice Date': 'Invoice Date',
    'Terms and Conditions': 'Terms and Conditions',
    'Additional Notes': 'Additional Notes',
    'Payment Terms': 'Payment Terms',
    'Select Payment Terms': 'Select Payment Terms',
    'Net 30': 'Net 30',
    'Net 15': 'Net 15',
    'Due on Receipt': 'Due on Receipt',
    'Custom': 'Custom',
    'Upload file': 'Upload file',
    'Drag and drop files here': 'Drag and drop files here',
    'No file chosen': 'No file chosen',
    'Enter terms and conditions': 'Enter terms and conditions',
    'Enter additional notes': 'Enter additional notes',
    'Quotation': 'Quotation',
    
    // Customer management
    'Add Customer': 'Add Customer',
    'Customer Code': 'Customer Code',
    'Customer Name': 'Customer Name',
    'Search customers...': 'Search customers...',
    'No customers found': 'No customers found',
    'Add Your First Customer': 'Add Your First Customer',
    'Accounts Receivables': 'Accounts Receivables',
    'Cash': 'Cash',
    'Bank': 'Bank',
    'Create associated account in Chart of Accounts': 'Create associated account in Chart of Accounts',
    'VAT Registration Number': 'VAT Registration Number',
    'Opening Balance': 'Opening Balance',
    'Outstanding Balance': 'Outstanding Balance',
    'Add Your Custom Fields': 'Add Your Custom Fields',
    'Billing Address': 'Billing Address',
    'Street Name': 'Street Name',
    'Postal Code': 'Postal Code',
    'Saudi Arabia': 'Saudi Arabia',
    'UAE': 'UAE',
    'Kuwait': 'Kuwait',
    'Loading customers...': 'Loading customers...',
    'Failed to load customers. Please try again.': 'Failed to load customers. Please try again.',
    'No customers found matching your search': 'No customers found matching your search',
    'Try adjusting your search terms': 'Try adjusting your search terms',
    'Create your first customer to get started': 'Create your first customer to get started',
    'Total Outstanding': 'Total Outstanding',
    'All rights reserved © 2025 Second Support': 'All rights reserved © 2025 Second Support',
    'Second Support Accounting': 'Second Support Accounting',
    'Second Support': 'Second Support',
    'From': 'From',
    'To': 'To',
    'Apply': 'Apply',
    'Clear': 'Clear',
    'Download Excel': 'Download Excel',
    'Download PDF': 'Download PDF',
    'Excel file downloaded successfully': 'Excel file downloaded successfully',
    'PDF file downloaded successfully': 'PDF file downloaded successfully',
    'Generated on': 'Generated on',
    'Please allow pop-ups to enable printing': 'Please allow pop-ups to enable printing',
    'Importing...': 'Importing...',
    'Import Successful': 'Import Successful',
    'Import Failed': 'Import Failed',
    'Import Completed with Errors': 'Import Completed with Errors',
    'Successfully imported ': 'Successfully imported ',
    ' customers.': ' customers.',
    ' customers failed to import.': ' customers failed to import.',
    'Unsupported file format. Please use CSV or Excel files.': 'Unsupported file format. Please use CSV or Excel files.',
    'File must contain at least a header row and one data row.': 'File must contain at least a header row and one data row.',
    'Missing required columns: ': 'Missing required columns: ',
    'Row ': 'Row ',
    ': Customer Name and Account are required fields.': ': Customer Name and Account are required fields.',
    'No valid customer data found in the file.': 'No valid customer data found in the file.',
    'An error occurred during import.': 'An error occurred during import.',
    'Required columns not found. Please ensure your file has columns for Customer Name and Account.': 'Required columns not found. Please ensure your file has columns for Customer Name and Account.',
    
    // Quotations (only unique keys)
    'Quotations': 'Quotations',
    'Add Quotation': 'Add Quotation',
    'Reference ID': 'Reference ID',
    'Issue Date': 'Issue Date',
    'Discount Amount': 'Discount Amount',
    'Vat %': 'Vat %',
    'Sent': 'Sent',
    'Accepted': 'Accepted',
    'Declined': 'Declined',
    'Expired': 'Expired',
    'All Status': 'All Status',
    'Search quotations...': 'Search quotations...',
    'No quotations found': 'No quotations found',
    'Delete Quotation': 'Delete Quotation',
    'Are you sure you want to delete this quotation? This action cannot be undone.': 'Are you sure you want to delete this quotation? This action cannot be undone.',
    'Quotation deleted successfully': 'Quotation deleted successfully',
    'Failed to delete quotation': 'Failed to delete quotation',
    
    // Proforma Invoices
    'Proforma invoices': 'Proforma invoices',
    'Proforma Invoice': 'Proforma Invoice',
    'Add Proforma Invoice': 'Add Proforma Invoice',
    'Create Proforma Invoice': 'Create Proforma Invoice',
    'Proforma Invoice Details': 'Proforma Invoice Details',
    'No proforma invoices found': 'No proforma invoices found',
    'Delete Proforma Invoice': 'Delete Proforma Invoice',
    'Are you sure you want to delete this proforma invoice? This action cannot be undone.': 'Are you sure you want to delete this proforma invoice? This action cannot be undone.',
    'Proforma invoice created successfully': 'Proforma invoice created successfully',
    'Failed to create proforma invoice': 'Failed to create proforma invoice',
    'Proforma invoice deleted successfully': 'Proforma invoice deleted successfully',
    'Failed to delete proforma invoice': 'Failed to delete proforma invoice',
    'Search proforma invoices...': 'Search proforma invoices...',
    'Add new record': 'Add new record',
    'Clear all': 'Clear all',
    'Products / Services': 'Products / Services',
    'Select product/service': 'Select product/service',
    'Terms Exclusive': 'Terms Exclusive',
    'Gross': 'Gross',
    'Total Amount': 'Total Amount',
    'Creating...': 'Creating...',
    'Pick a date': 'Pick a date',
    'Please select customer': 'Please select customer',
    'Select a customer to view details': 'Select a customer to view details',
    
    // Sidebar Navigation
    'Sales': 'Sales',
    'Customers': 'Customers',
    'Customer List': 'Customer List',
    'Items': 'Items',
    'Purchases': 'Purchases',
    'Accountant': 'Accountant',
    'Banking': 'Banking',
    'Documents': 'Documents',
    'Settings': 'Settings',
    'Reports and Analytics': 'Reports and Analytics',
    'Language': 'Language',
    'English': 'English',
    'العربية': 'Arabic',
    
    // Settings Menu
    'General Settings': 'General Settings',
    'Accounting Settings': 'Accounting Settings',
    'Financial Years': 'Financial Years',
    'Forms Design': 'Forms Design',
    'Taxes': 'Taxes',
  },
  ar: {
    // Login page
    'VoM Accounting Platform': 'منصة محاسبة Second Support',
    'Sign in to your account': 'تسجيل الدخول إلى حسابك',
    'Email Address': 'عنوان البريد الإلكتروني',
    'Password': 'كلمة المرور',
    "I'm not a robot": 'لست روبوتاً',
    'Sign In': 'تسجيل الدخول',
    'Logout': 'تسجيل الخروج',
    'Forgot your password?': 'نسيت كلمة المرور؟',
    'Test Credentials': 'بيانات الاختبار',
    
    // Dashboard
    'VoM Accounting': 'محاسبة الصوت المال',
    'Financial Management Platform': 'منصة الإدارة المالية',
    'Overview': 'نظرة عامة',
    'Invoices': 'الفواتير',
    'Expenses': 'المصروفات',
    'Reports': 'التقارير',
    'ZATCA Compliance': 'امتثال هيئة الزكاة والضريبة والجمارك',
    'Quick Actions': 'إجراءات سريعة',
    'New Invoice': 'فاتورة جديدة',
    'Import Data': 'استيراد البيانات',
    
    // Common UI
    'Welcome': 'مرحباً',
    'Last visit today 1 day ago': 'آخر زيارة اليوم منذ يوم واحد',
    'Export': 'تصدير',
    'Copy': 'نسخ',
    'Print': 'طباعة',
    'Import': 'استيراد',
    'Filter': 'تصفية',
    'Show': 'عرض',
    'entries': 'إدخالات',
    'Actions': 'الإجراءات',
    'Active': 'نشط',
    'Inactive': 'غير نشط',
    'Back': 'العودة',
    'Create': 'إنشاء',
    'Code': 'الرمز',
    'Account': 'الحساب',
    'Phone': 'الهاتف',
    'Email': 'البريد الإلكتروني',
    'City': 'المدينة',
    'Country': 'البلد',
    'Value of Money': 'قيمة المال',
    'All rights reserved © 2025 VoM': 'جميع الحقوق محفوظة © 2025 قيمة المال',
    
    // Financial Overview
    'Financial Overview': 'النظرة المالية العامة',
    'Track your business performance and key metrics': 'تتبع أداء عملك والمقاييس الرئيسية',
    'Total Revenue': 'إجمالي الإيرادات',
    'Active Invoices': 'الفواتير النشطة',
    'Total Customers': 'إجمالي العملاء',
    'Monthly Expenses': 'المصروفات الشهرية',
    'Revenue Trend': 'اتجاه الإيرادات',
    'Recent Invoices': 'الفواتير الأخيرة',
    'View All Invoices': 'عرض جميع الفواتير',
    
    // Invoice Management
    'Invoice Management': 'إدارة الفواتير',
    'Create, manage and track your invoices': 'إنشاء وإدارة وتتبع فواتيرك',
    'Invoice #': 'رقم الفاتورة',
    'Amount': 'المبلغ',
    'Status': 'الحالة',
    'Date': 'التاريخ',
    'Customer': 'العميل',
    'Paid': 'مدفوع',
    'Pending': 'في الانتظار',
    'Draft': 'مسودة',
    'Overdue': 'متأخر',
    'Due Date': 'تاريخ الاستحقاق',
    'Total': 'الإجمالي',
    'Subtotal': 'المجموع الفرعي',
    'Tax': 'الضريبة',
    'Discount': 'الخصم',
    'Item': 'البند',
    'Description': 'الوصف',
    'Quantity': 'الكمية',
    'Price': 'السعر',
    'Add Item': 'إضافة بند',
    'Save Invoice': 'حفظ الفاتورة',
    'Send Invoice': 'إرسال الفاتورة',
    'Preview': 'معاينة',
    'Cancel': 'إلغاء',
    'Save': 'حفظ',
    'Edit': 'تحرير',
    'Delete': 'حذف',
    'View': 'عرض',
    'Invoice Date': 'تاريخ الفاتورة',
    'Terms and Conditions': 'الشروط والأحكام',
    'Additional Notes': 'ملاحظات إضافية',
    'Payment Terms': 'شروط الدفع',
    'Select Payment Terms': 'اختر شروط الدفع',
    'Net 30': 'صافي 30',
    'Net 15': 'صافي 15',
    'Due on Receipt': 'مستحق عند الاستلام',
    'Custom': 'مخصص',
    'Upload file': 'رفع ملف',
    'Drag and drop files here': 'اسحب وأفلت الملفات هنا',
    'No file chosen': 'لم يتم اختيار ملف',
    'Enter terms and conditions': 'أدخل الشروط والأحكام',
    'Enter additional notes': 'أدخل ملاحظات إضافية',
    'Quotation': 'عرض السعر',
    
    // Customer management
    'Add Customer': 'إضافة عميل',
    'Customer Code': 'رمز العميل',
    'Customer Name': 'اسم العميل',
    'Search customers...': 'البحث عن العملاء...',
    'No customers found': 'لم يتم العثور على عملاء',
    'Add Your First Customer': 'أضف عميلك الأول',
    'Accounts Receivables': 'حسابات المدينين',
    'Cash': 'نقد',
    'Bank': 'البنك',
    'Create associated account in Chart of Accounts': 'إنشاء حساب مرتبط في دليل الحسابات',
    'VAT Registration Number': 'رقم تسجيل ضريبة القيمة المضافة',
    'Opening Balance': 'الرصيد الافتتاحي',
    'Outstanding Balance': 'الرصيد المستحق',
    'Add Your Custom Fields': 'أضف حقولك المخصصة',
    'Billing Address': 'عنوان الفوترة',
    'Street Name': 'اسم الشارع',
    'Postal Code': 'الرمز البريدي',
    'Saudi Arabia': 'المملكة العربية السعودية',
    'UAE': 'الإمارات العربية المتحدة',
    'Kuwait': 'الكويت',
    'Loading customers...': 'تحميل العملاء...',
    'Failed to load customers. Please try again.': 'فشل في تحميل العملاء. يرجى المحاولة مرة أخرى.',
    'No customers found matching your search': 'لم يتم العثور على عملاء مطابقين لبحثك',
    'Try adjusting your search terms': 'جرب تعديل شروط البحث',
    'Create your first customer to get started': 'أنشئ أول عميل للبدء',
    'Total Outstanding': 'إجمالي المستحقات',
    'All rights reserved © 2025 Second Support': 'جميع الحقوق محفوظة © 2025 Second Support',
    'Second Support Accounting': 'محاسبة Second Support',
    'Second Support': 'Second Support',
    'From': 'من',
    'To': 'إلى',
    'Apply': 'تطبيق',
    'Clear': 'مسح',
    'Download Excel': 'تحميل Excel',
    'Download PDF': 'تحميل PDF',
    'Excel file downloaded successfully': 'تم تحميل ملف Excel بنجاح',
    'PDF file downloaded successfully': 'تم تحميل ملف PDF بنجاح',
    'Generated on': 'تم الإنشاء في',
    'Please allow pop-ups to enable printing': 'يرجى السماح بالنوافذ المنبثقة لتمكين الطباعة',
    'Importing...': 'جارٍ الاستيراد...',
    'Import Successful': 'تم الاستيراد بنجاح',
    'Import Failed': 'فشل الاستيراد',
    'Import Completed with Errors': 'تم الاستيراد مع وجود أخطاء',
    'Successfully imported ': 'تم استيراد ',
    ' customers.': ' عميل بنجاح.',
    ' customers failed to import.': ' عميل فشل في الاستيراد.',
    'Unsupported file format. Please use CSV or Excel files.': 'تنسيق الملف غير مدعوم. يرجى استخدام ملفات CSV أو Excel.',
    'File must contain at least a header row and one data row.': 'يجب أن يحتوي الملف على صف رؤوس وصف بيانات واحد على الأقل.',
    'Missing required columns: ': 'أعمدة مطلوبة مفقودة: ',
    'Row ': 'الصف ',
    ': Customer Name and Account are required fields.': ': اسم العميل والحساب حقول مطلوبة.',
    'No valid customer data found in the file.': 'لم يتم العثور على بيانات عميل صالحة في الملف.',
    'An error occurred during import.': 'حدث خطأ أثناء الاستيراد.',
    'Required columns not found. Please ensure your file has columns for Customer Name and Account.': 'الأعمدة المطلوبة غير موجودة. يرجى التأكد من أن ملفك يحتوي على أعمدة لاسم العميل والحساب.',
    
    // Quotations (only unique keys in Arabic)
    'Quotations': 'عروض الأسعار',
    'Add Quotation': 'إضافة عرض سعر',
    'Reference ID': 'رقم المرجع',
    'Issue Date': 'تاريخ الإصدار',
    'Discount Amount': 'مبلغ الخصم',
    'Vat %': 'ضريبة القيمة المضافة %',
    'Sent': 'مرسل',
    'Accepted': 'مقبول',
    'Declined': 'مرفوض',
    'Expired': 'منتهي الصلاحية',
    'All Status': 'جميع الحالات',
    'Search quotations...': 'البحث في عروض الأسعار...',
    'No quotations found': 'لم يتم العثور على عروض أسعار',
    'Delete Quotation': 'حذف عرض السعر',
    'Are you sure you want to delete this quotation? This action cannot be undone.': 'هل أنت متأكد من أنك تريد حذف عرض السعر هذا؟ لا يمكن التراجع عن هذا الإجراء.',
    'Quotation deleted successfully': 'تم حذف عرض السعر بنجاح',
    'Failed to delete quotation': 'فشل في حذف عرض السعر',
    
    // Proforma Invoices
    'Proforma invoices': 'الفواتير الأولية',
    'Proforma Invoice': 'فاتورة أولية',
    'Add Proforma Invoice': 'إضافة فاتورة أولية',
    'Create Proforma Invoice': 'إنشاء فاتورة أولية',
    'Proforma Invoice Details': 'تفاصيل الفاتورة الأولية',
    'No proforma invoices found': 'لم يتم العثور على فواتير أولية',
    'Delete Proforma Invoice': 'حذف الفاتورة الأولية',
    'Are you sure you want to delete this proforma invoice? This action cannot be undone.': 'هل أنت متأكد من أنك تريد حذف هذه الفاتورة الأولية؟ لا يمكن التراجع عن هذا الإجراء.',
    'Proforma invoice created successfully': 'تم إنشاء الفاتورة الأولية بنجاح',
    'Failed to create proforma invoice': 'فشل في إنشاء الفاتورة الأولية',
    'Proforma invoice deleted successfully': 'تم حذف الفاتورة الأولية بنجاح',
    'Failed to delete proforma invoice': 'فشل في حذف الفاتورة الأولية',
    'Search proforma invoices...': 'البحث في الفواتير الأولية...',
    'Add new record': 'إضافة سجل جديد',
    'Clear all': 'مسح الكل',
    'Products / Services': 'المنتجات / الخدمات',
    'Select product/service': 'اختر منتج/خدمة',
    'Terms Exclusive': 'الشروط الحصرية',
    'Gross': 'الإجمالي',
    'Total Amount': 'المبلغ الإجمالي',
    'Creating...': 'جاري الإنشاء...',
    'Pick a date': 'اختر تاريخ',
    'Please select customer': 'يرجى اختيار العميل',
    'Select a customer to view details': 'اختر عميل لعرض التفاصيل',
    
    // Sidebar Navigation
    'Sales': 'المبيعات',
    'Customers': 'العملاء',
    'Customer List': 'قائمة العملاء',
    'Items': 'الأصناف',
    'Purchases': 'المشتريات',
    'Accountant': 'المحاسب',
    'Banking': 'البنوك',
    'Documents': 'المستندات',
    'Settings': 'الإعدادات',
    'Reports and Analytics': 'التقارير والتحليلات',
    'Language': 'اللغة',
    'English': 'English',
    'العربية': 'العربية',
    
    // Settings Menu
    'General Settings': 'الإعدادات العامة',
    'Accounting Settings': 'إعدادات المحاسبة',
    'Financial Years': 'السنوات المالية',
    'Forms Design': 'تصميم النماذج',
    'Taxes': 'الضرائب',
  }
};

const LanguageContext = createContext<LanguageContextType | undefined>(undefined);

export function LanguageProvider({ children }: { children: React.ReactNode }) {
  const [language, setLanguage] = useState<Language>('en');

  const isRTL = language === 'ar';

  useEffect(() => {
    const savedLanguage = localStorage.getItem('language') as Language;
    if (savedLanguage && ['en', 'ar'].includes(savedLanguage)) {
      setLanguage(savedLanguage);
    }
  }, []);

  useEffect(() => {
    localStorage.setItem('language', language);
    document.documentElement.lang = language;
    document.documentElement.dir = isRTL ? 'rtl' : 'ltr';
  }, [language, isRTL]);

  const t = (key: string): string => {
    return (translations[language] as any)[key] || key;
  };

  return (
    <LanguageContext.Provider value={{ language, setLanguage, t, isRTL }}>
      {children}
    </LanguageContext.Provider>
  );
}

export function useLanguage() {
  const context = useContext(LanguageContext);
  if (context === undefined) {
    throw new Error('useLanguage must be used within a LanguageProvider');
  }
  return context;
}